import matplotlib.pyplot as plt
from prepare import dataset

figure, axis = plt.subplots(10, 2) 
plt.style.use('fivethirtyeight')
data = dataset.copy()
data_autism = data.query('autism==1')
data_nonautism = data.query('autism==0')
print(data_autism.count())
print(data_nonautism.count())
# Histogram of country distribution
# plt.style.use('fivethirtyeight')
# plt.hist(data['country_of_res'].dropna(), bins = 100, edgecolor = 'k')
# plt.xlabel('Country of residence')
# plt.xticks(rotation=90)
# plt.ylabel('Diagnosed with autism')
# plt.title('App diagnosed with autism per country')
# plt.show()

# Let's buld histograms on each of 10 questions to analyze what questions are giving the parametrized answers
# We use only rows where autism = 1 (Class/ASD column is showing the per app diagnosis)
axis[0,0].hist(data_autism['A1_Score'], bins=100, edgecolor = 'k')
axis[0,0].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[0,0].set_title('I  often  notice  small  sounds \n when  others  do not \n Autism diagnosed', fontsize=10)
axis[0,1].hist(data_nonautism['A1_Score'], bins=100, edgecolor = 'k')
axis[0,1].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[0,1].set_title('I  often  notice  small  sounds \n when  others  do not \n Autism not diagnosed', fontsize=10)
axis[1,0].hist(data_autism['A2_Score'],bins=100, edgecolor = 'k')
axis[1,0].set_xlabel('Definitely disagree or slightly disagree')
axis[1,0].set_title('I   usually   concentrate   more   on  \n the   whole picture, rather than the small details\n Autism diagnosed',fontsize=10)
axis[1,1].hist(data_nonautism['A2_Score'],bins=100, edgecolor = 'k')
axis[1,1].set_xlabel('Definitely disagree or slightly disagree')
axis[1,1].set_title('I   usually   concentrate   more   on  \n the   whole picture, rather than the small details\n Autism not diagnosed',fontsize=10)
axis[2,0].hist(data_autism['A3_Score'],bins=100, edgecolor = 'k')
axis[2,0].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[2,0].set_title('I  find  it  easy  to  do  more  than \n one  thing  at once\n Autism diagnosed', fontsize=10)
axis[2,1].hist(data_nonautism['A3_Score'],bins=100, edgecolor = 'k')
axis[2,1].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[2,1].set_title('I  find  it  easy  to  do  more  than \n one  thing  at once\n Autism not diagnosed', fontsize=10)
axis[3,0].hist(data_autism['A4_Score'],bins=100, edgecolor = 'k')
axis[3,0].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[3,0].set_title('If there is an interruption, I can switch \n back to what I was doing very quickly\n Autism diagnosed', fontsize=10)
axis[3,1].hist(data_nonautism['A4_Score'],bins=100, edgecolor = 'k')
axis[3,1].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[3,1].set_title('If there is an interruption, I can switch \n back to what I was doing very quickly\n Autism not diagnosed', fontsize=10)
axis[4,0].hist(data_autism['A5_Score'],bins=100, edgecolor = 'k')
axis[4,0].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[4,0].set_title('I find it easy to ‘read between the lines’\n whensomeone is talking to me \n Autism diagnosed', fontsize=10)
axis[4,1].hist(data_nonautism['A5_Score'],bins=100, edgecolor = 'k')
axis[4,1].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[4,1].set_title('I find it easy to ‘read between the lines’\n whensomeone is talking to me \n Autism not diagnosed', fontsize=10)
axis[5,0].hist(data_autism['A6_Score'],bins=100, edgecolor = 'k')
axis[5,0].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[5,0].set_title('I  know  how  to  tell  if  someone \n  listening  to  meis getting bored\n Autism diagnosed', fontsize=10)
axis[5,1].hist(data_nonautism['A6_Score'],bins=100, edgecolor = 'k')
axis[5,1].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[5,1].set_title('I  know  how  to  tell  if  someone \n  listening  to  meis getting bored\n Autism not diagnosed', fontsize=10)
axis[6,0].hist(data_autism['A7_Score'],bins=100, edgecolor = 'k')
axis[6,0].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[6,0].set_title('When  I’m  reading  a  story  I  find  \n it  difficult  towork out the characters’ intentions\n Autism diagnosed', fontsize=10)
axis[6,1].hist(data_nonautism['A7_Score'],bins=100, edgecolor = 'k')
axis[6,1].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[6,1].set_title('When  I’m  reading  a  story  I  find  \n it  difficult  towork out the characters’ intentions\n Autism not diagnosed', fontsize=10)
axis[7,0].hist(data_autism['A8_Score'],bins=100, edgecolor = 'k')
axis[7,0].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[7,0].set_title('I  like to collect information about \n categories of things \n Autism diagnosed', fontsize=10)
axis[7,1].hist(data_nonautism['A8_Score'],bins=100, edgecolor = 'k')
axis[7,1].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[7,1].set_title('I  like to collect information about \n categories of things \n Autism not diagnosed', fontsize=10)
axis[8,0].hist(data_autism['A9_Score'],bins=100, edgecolor = 'k')
axis[8,0].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[8,0].set_title('I  find  it  easy  to  work  out  what \n someone  is thinking or feeling just by looking \n at their face\n Autism diagnosed', fontsize=10)
axis[8,1].hist(data_nonautism['A9_Score'],bins=100, edgecolor = 'k')
axis[8,1].set_xlabel('Definitely disagree or slightly disagree', fontsize=10)
axis[8,1].set_title('I  find  it  easy  to  work  out  what \n someone  is thinking or feeling just by looking \n at their face\n Autism not diagnosed', fontsize=10)
axis[9,0].hist(data_autism['A10_Score'],bins=100, edgecolor = 'k')
axis[9,0].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[9,0].set_title('I find it difficult to work out people’s \n intentions\n Autism diagnosed', fontsize=10)
axis[9,1].hist(data_nonautism['A10_Score'],bins=100, edgecolor = 'k')
axis[9,1].set_xlabel('Definitely agree or slightly agree', fontsize=10)
axis[9,1].set_title('I find it difficult to work out people’s \n intentions\n Autism not diagnosed', fontsize=10)
plt.show()

# As per the outcome, it seems like we cannot really expell any of the 10 questions (see Bar_chart_answers_distribution.png)
